blank_issues_enabled: false

contact_links:
  - name: Statamic Core
    url: https://github.com/statamic/cms/issues/new/choose
    about: "This repository is for the Statamic Eloquent Driver. If you're experiencing issues with Statamic itself, please open an issue on the `statamic/cms` repository."
